---
# Source: kargo/templates/users/cluster-roles.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kargo-admin
  labels:
    helm.sh/chart: kargo-0.1.0
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v0.1.0"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ""
  resources:
  - events
  - namespaces
  # secrets permissions are granted dynamically at the project-level
  - serviceaccounts # writes on serviceaccounts are granted dynamically at the project-level
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings # writes on rolebindings are granted dynamically at the project-level
  - roles # writes on roles are granted dynamically at the project-level
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kargo.akuity.io
  resources:
  - freights
  - projects
  - stages
  - warehouses
  verbs:
  - "*" # full access to all mutable Kargo resource types
- apiGroups:
  - kargo.akuity.io
  resources:
  - stages
  verbs:
  - promote # promotion permission for all stages
- apiGroups:
  - kargo.akuity.io
  resources:
  - promotions
  verbs: # nearly full access to all promotions, but they are immutable
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - kargo.akuity.io
  resources:
  - freights/status
  verbs:
  - patch # for manual approvals
---
# Source: kargo/templates/users/cluster-roles.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kargo-viewer
  labels:
    helm.sh/chart: kargo-0.1.0
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v0.1.0"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ""
  resources:
  - events
  - namespaces
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kargo.akuity.io
  resources:
  - freights
  - projects
  - promotions
  - stages
  - warehouses
  verbs:
  - get
  - list
  - watch
