---
# Source: kargo/templates/users/service-accounts.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kargo-admin
  namespace: kargo-kargo
  labels:
    helm.sh/chart: kargo-0.1.0
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v0.1.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: kargo/templates/users/service-accounts.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kargo-viewer
  namespace: kargo-kargo
  labels:
    helm.sh/chart: kargo-0.1.0
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v0.1.0"
    app.kubernetes.io/managed-by: Helm
