---
# Source: kargo/templates/controller/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kargo-controller
  namespace: kargo-kargo
  labels:
    helm.sh/chart: kargo-0.1.0
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v0.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
data:
  API_SERVER_BASE_URL: https://localhost
  LOG_LEVEL: "INFO"
  GLOBAL_CREDENTIALS_NAMESPACES: ""
  GITCLIENT_NAME: "Kargo"
  GITCLIENT_EMAIL: "no-reply@kargo.io"
  GITCLIENT_SIGNING_KEY_TYPE: "gpg"
  ARGOCD_INTEGRATION_ENABLED: "true"
  ARGOCD_NAMESPACE: openshift-gitops
  ARGOCD_WATCH_ARGOCD_NAMESPACE_ONLY: "false"
  ROLLOUTS_INTEGRATION_ENABLED: "false"
