# This is needed due to bug in Kargo.
# Refer: https://github.com/akuity/kargo/issues/2520
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kargo-management-controller-namespace-delete
rules:
  - verbs:
      - delete
    apiGroups:
      - ''
    resources:
      - namespaces
