apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterrole-kargo-management-controller-namespace-delete.yaml
  - clusterrolebinding-kargo-management-controller-namespace-delete.yaml
  - namespace.yaml
