apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kargo-management-controller-namespace-delete
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-management-controller-namespace-delete
subjects:
- kind: ServiceAccount
  name: kargo-management-controller
  namespace: kargo
