apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: garbage-collector
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kargo
    app.kubernetes.io/version: v0.1.0
    helm.sh/chart: kargo-0.1.0
  name: kargo-garbage-collector
  namespace: kargo
