apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
    eso.pfb.com.au/cluster-secret-store: aws
  name: kargo
